#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & polybar &

bspc monitor -d A¹ B² C³ D⁴

bspc config window_gap            5

bspc config split_ratio           0.5
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

feh --bg-fill ~/Pictures/Wallpapers/City.jpg
